import "~/styles/globals.css";
import { inter } from "~/app/fonts";

import { GoogleAnalytics } from "@next/third-parties/google";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { TopNav } from "./_components/topnav";
import { Footer } from "./_components/footer";
import { Toaster } from "~/components/ui/toaster";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "OpenMat",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{ children: React.ReactNode; modal: React.ReactNode }>) {
  return (
    <SessionProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className={`${inter.className} antialiased`}>
          <NextTopLoader />
          <div className="grid min-h-screen grid-rows-[auto,1fr]">
            <TopNav />
            {children}
            {modal}
            <div id="modal-root" />
            <Toaster />
            <Footer />
          </div>
        </body>
        {/* <GoogleAnalytics gaId="G-BNX08YMCR9" /> */}
      </html>
    </SessionProvider>
  );
}
